### ISSUE TITLE
source_setenv function is redundant

### ISSUE THREAD

**Issue by horosgrisa** [jocelynmallon/zshmarks#20]
I think that [source_setenv](https://github.com/jocelynmallon/zshmarks/blob/master/zshmarks.plugin.zsh#L48) is redundant and insecure. I propose to remove this function. But if you need similar functionality, you can use my plugin for zsh: [autoenv](https://github.com/horosgrisa/autoenv)

**Comment by jocelynmallon** [comment]
Agreed, this is really beyond the scope of zshmarks in the first place, your plugin is better suited for this kind of task.
