### ISSUE TITLE
Add new installation method

### ISSUE THREAD

**Issue by b4b4r07** [jocelynmallon/zshmarks#25]
Hi,

Your zshmarks is an amazing zsh plugin! I appreciate it.
BTW, by using [zplug](https://github.com/b4b4r07/zplug), we can easily install this plugin.

Would you add this installation method to your README?

```console
$ zplug "jocelynmallon/zshmarks"
```

**Comment by jocelynmallon** [comment]
Added, thanks.

**Comment by b4b4r07** [comment]
Very cool! Thanks.
