### ISSUE TITLE
Tab completion fails in prezto

### ISSUE THREAD

**Issue by protist** [jocelynmallon/zshmarks#27]
I just made the jump from oh-my-zsh to prezto, and tried to install zshmarks in the latter. I cloned the zshmarks repository directly into `/usr/lib/prezto/modules/`, and activated the plugin via `~/.zpreztorc`. The commands work fine (e.g. `jump foo`), but tab completion is broken for me.
```
$ jump <TAB>
(eval):1: _jump_showmarks_deletemark: function definition file not found
(eval):1: _jump_showmarks_deletemark: function definition file not found
```
Arch Linux: up-to-date
zsh 5.2
prezto-git: up-to-date
zshmarks: up-to-date

**Comment by protist** [comment]
I'm happy to troubleshoot more if this is helpful, but please let me know if you have abandoned prezto support, so that I can investigate other options. Thank you.

**Comment by jocelynmallon** [comment]
Hey, sorry, it's not "abandoned" but at the moment I'm physically homeless and don't have access to a computer anymore, so I can't troubleshoot this.

I only ever had completion issues when I would switch back and forth between different shell frameworks for testing, and whenever that happened, simply trashing the zcompdump file and manually running "compinit" fixed the issues.

E.g.
    rm -f ~/.zcompdump; compinit

**Comment by protist** [comment]
Thanks for the reply, and I'm sorry to hear about your situation. FWIW removing `~/.zcompdump` and running `compinit` didn't seem to help; I still get the same error.

I'm happy to troubleshoot more for you, if you can direct me. However, obviously your situation is suboptimal, and I understand that this is in no way a priority for you. Hope you sort things out, and thanks again for the reply.

**Comment by protist** [comment]
It [turns out](http://stackoverflow.com/a/10585017/1944384) that there are multiple `~/.zcompdump*` files, including `~/.zcompdump-<COMPUTER NAME>-<VERSION>` and `~/.zcompdump.zwc`. Deleting all of these (i.e. `rm ~/.zcompdump*`) fixed this issue for me, without needing to run `compinit`. Thanks again for the help and good luck again for the future.
